export const PAESI: string[] = [
  'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Arabia Saudita', 'Argentina', 'Armenia',
  'Australia', 'Austria', 'Azerbaijan',
  'Bangladesh', 'Belgio', 'Bielorussia', 'Bolivia', 'Bosnia ed Erzegovina', 'Botswana',
  'Brasile', 'Bulgaria', 'Burkina Faso', 'Burundi',
  'Cambogia', 'Camerun', 'Canada', 'Cile', 'Cina', 'Colombia', 'Congo',
  'Corea del Nord', 'Corea del Sud', 'Costa Rica', "Costa d'Avorio", 'Croazia', 'Cuba',
  'Danimarca',
  'Ecuador', 'Egitto', 'El Salvador', 'Emirati Arabi Uniti', 'Eritrea', 'Etiopia',
  'Filippine', 'Finlandia', 'Francia',
  'Georgia', 'Germania', 'Ghana', 'Giappone', 'Giordania', 'Grecia', 'Guatemala', 'Guinea',
  'Haiti', 'Honduras',
  'India', 'Indonesia', 'Iran', 'Iraq', 'Irlanda', 'Israele', 'Italia',
  'Kenya',
  'Laos', 'Libano', 'Libia',
  'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Marocco', 'Messico', 'Moldova', 'Mongolia',
  'Mozambico', 'Myanmar',
  'Nepal', 'Nicaragua', 'Niger', 'Nigeria', 'Norvegia', 'Nuova Zelanda',
  'Olanda',
  'Pakistan', 'Panama', 'Paraguay', 'Perù', 'Polonia', 'Portogallo',
  'Repubblica Ceca', 'Repubblica Dominicana', 'Romania', 'Ruanda', 'Russia',
  'Senegal', 'Serbia', 'Sierra Leone', 'Siria', 'Somalia', 'Spagna', 'Sri Lanka',
  'Sudafrica', 'Sudan', 'Svezia', 'Svizzera',
  'Tanzania', 'Thailandia', 'Tunisia', 'Turchia',
  'Uganda', 'Ucraina', 'Ungheria', 'Uruguay', 'Uzbekistan',
  'Venezuela', 'Vietnam',
  'Yemen',
  'Zambia', 'Zimbabwe',
];
