import ExcelJS from 'exceljs';
import type { Order } from '@/types';

interface CartExportItem {
  productCode: string;
  productName: string;
  quantity: number;
  unitPrice: number;
  categoryName?: string;
}

interface CartExportPayload {
  items: CartExportItem[];
  customerCode?: string;
  companyName?: string;
}

export async function generateCartExcel(payload: CartExportPayload): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'ON EARTH B2B';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Order', {
    properties: { tabColor: { argb: 'FFC4A882' } },
  });

  // Simple ERP import format: Code | Qty
  sheet.columns = [
    { header: 'Code', key: 'code', width: 18 },
    { header: 'Qty', key: 'qty', width: 10 },
    { header: 'Product Name', key: 'name', width: 40 },
    { header: 'Unit Price', key: 'unit', width: 14 },
    { header: 'Total', key: 'total', width: 14 },
    { header: 'Category', key: 'cat', width: 24 },
  ];

  // Style header
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: 'FF1C1C1C' }, size: 9 };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFF5EFE6' },
  };
  headerRow.height = 22;
  headerRow.alignment = { vertical: 'middle' };
  headerRow.border = {
    bottom: { style: 'thin', color: { argb: 'FFE8E2D9' } },
  };

  // Data rows
  let totalValue = 0;
  let totalQty = 0;
  payload.items.forEach((item, i) => {
    const total = item.unitPrice * item.quantity;
    totalValue += total;
    totalQty += item.quantity;

    const row = sheet.addRow({
      code: item.productCode,
      qty: item.quantity,
      name: item.productName,
      unit: item.unitPrice,
      total: total,
      cat: item.categoryName || '',
    });

    if (i % 2 === 0) {
      row.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFFAFAF7' },
      };
    }

    row.getCell('unit').numFmt = '€#,##0.00';
    row.getCell('total').numFmt = '€#,##0.00';
    row.font = { size: 9 };
    row.alignment = { vertical: 'middle' };
  });

  // Summary row
  const summaryRow = sheet.addRow({
    code: '',
    qty: totalQty,
    name: 'TOTAL',
    unit: '',
    total: totalValue,
    cat: '',
  });
  summaryRow.font = { bold: true, size: 9 };
  summaryRow.getCell('name').alignment = { horizontal: 'right' };
  summaryRow.getCell('total').numFmt = '€#,##0.00';
  summaryRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFF5EFE6' },
  };
  summaryRow.border = {
    top: { style: 'thin', color: { argb: 'FFCCBBAA' } },
  };

  // Metadata sheet
  const metaSheet = workbook.addWorksheet('Info');
  metaSheet.addRow(['Field', 'Value']);
  metaSheet.addRow(['Customer Code', payload.customerCode || '']);
  metaSheet.addRow(['Company', payload.companyName || '']);
  metaSheet.addRow(['Collection', 'CASA 2027']);
  metaSheet.addRow(['Export Date', new Date().toISOString()]);
  metaSheet.addRow(['Generated by', 'ON EARTH B2B Platform']);

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export async function generateOrderExcel(order: Order): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'ON EARTH B2B';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Order', {
    properties: { tabColor: { argb: 'FFC4A882' } },
  });

  // Header info
  sheet.mergeCells('A1:F1');
  const titleCell = sheet.getCell('A1');
  titleCell.value = 'ON EARTH — CASA 2027';
  titleCell.font = { bold: true, size: 14, color: { argb: 'FF1C1C1C' } };
  titleCell.alignment = { horizontal: 'left', vertical: 'middle' };
  sheet.getRow(1).height = 30;

  sheet.addRow([]);
  sheet.addRow(['Order ID', order.id.slice(0, 8).toUpperCase()]);
  sheet.addRow(['Customer', order.customer?.companyName || '']);
  sheet.addRow(['Date', new Date(order.createdAt).toLocaleDateString('it-IT')]);
  sheet.addRow(['Status', order.status]);
  sheet.addRow([]);

  // Column headers
  sheet.columns = [
    { key: 'code', width: 18 },
    { key: 'qty', width: 8 },
    { key: 'name', width: 40 },
    { key: 'unit', width: 14 },
    { key: 'total', width: 14 },
    { key: 'cat', width: 24 },
  ];

  const headerRow = sheet.addRow(['Code', 'Qty', 'Product Name', 'Unit Price (€)', 'Total (€)', 'Category']);
  headerRow.font = { bold: true, size: 9 };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFF5EFE6' },
  };
  headerRow.height = 20;

  // Items
  order.items?.forEach((item, i) => {
    const row = sheet.addRow([
      item.product?.code || '',
      item.quantity,
      item.product?.name || '',
      Number(item.unitPrice),
      Number(item.subtotal),
      item.product?.category?.name || '',
    ]);

    row.getCell(4).numFmt = '€#,##0.00';
    row.getCell(5).numFmt = '€#,##0.00';
    row.font = { size: 9 };

    if (i % 2 === 0) {
      row.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFFAFAF7' },
      };
    }
  });

  // Total row
  const totalRow = sheet.addRow(['', order.totalItems, 'TOTAL', '', Number(order.totalValue), '']);
  totalRow.font = { bold: true, size: 9 };
  totalRow.getCell(5).numFmt = '€#,##0.00';

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
