import ExcelJS from 'exceljs';
import type { Order } from '@/types';

interface CartExportItem {
  productCode: string;
  productName: string;
  quantity: number;
  unitPrice: number;
  categoryName?: string;
}

interface CartExportPayload {
  items: CartExportItem[];
  customerCode?: string;
  companyName?: string;
}

export async function generateCartExcel(payload: CartExportPayload): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'ON EARTH B2B';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Order', {
    properties: { tabColor: { argb: 'FFC4A882' } },
  });

  // Simple ERP import format: Code | Qty
  sheet.columns = [
    { header: 'Code', key: 'code', width: 18 },
    { header: 'Qty', key: 'qty', width: 10 },
    { header: 'Product Name', key: 'name', width: 40 },
    { header: 'Unit Price', key: 'unit', width: 14 },
    { header: 'Total', key: 'total', width: 14 },
    { header: 'Category', key: 'cat', width: 24 },
  ];

  // Style header
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: 'FF1C1C1C' }, size: 9 };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFF5EFE6' },
  };
  headerRow.height = 22;
  headerRow.alignment = { vertical: 'middle' };
  headerRow.border = {
    bottom: { style: 'thin', color: { argb: 'FFE8E2D9' } },
  };

  // Data rows
  let totalValue = 0;
  let totalQty = 0;
  payload.items.forEach((item, i) => {
    const total = item.unitPrice * item.quantity;
    totalValue += total;
    totalQty += item.quantity;

    const row = sheet.addRow({
      code: item.productCode,
      qty: item.quantity,
      name: item.productName,
      unit: item.unitPrice,
      total: total,
      cat: item.categoryName || '',
    });

    if (i % 2 === 0) {
      row.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFFAFAF7' },
      };
    }

    row.getCell('unit').numFmt = '€#,##0.00';
    row.getCell('total').numFmt = '€#,##0.00';
    row.font = { size: 9 };
    row.alignment = { vertical: 'middle' };
  });

  // Summary row
  const summaryRow = sheet.addRow({
    code: '',
    qty: totalQty,
    name: 'TOTAL',
    unit: '',
    total: totalValue,
    cat: '',
  });
  summaryRow.font = { bold: true, size: 9 };
  summaryRow.getCell('name').alignment = { horizontal: 'right' };
  summaryRow.getCell('total').numFmt = '€#,##0.00';
  summaryRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFF5EFE6' },
  };
  summaryRow.border = {
    top: { style: 'thin', color: { argb: 'FFCCBBAA' } },
  };

  // Metadata sheet
  const metaSheet = workbook.addWorksheet('Info');
  metaSheet.addRow(['Field', 'Value']);
  metaSheet.addRow(['Customer Code', payload.customerCode || '']);
  metaSheet.addRow(['Company', payload.companyName || '']);
  metaSheet.addRow(['Collection', 'CASA 2027']);
  metaSheet.addRow(['Export Date', new Date().toISOString()]);
  metaSheet.addRow(['Generated by', 'ON EARTH B2B Platform']);

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export async function generateOrderExcel(order: Order): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'ON EARTH B2B';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Ordine', {
    properties: { tabColor: { argb: 'FFC4A882' } },
  });

  // Title
  sheet.mergeCells('A1:K1');
  const titleCell = sheet.getCell('A1');
  titleCell.value = 'ON EARTH — CASA 2027';
  titleCell.font = { bold: true, size: 14, color: { argb: 'FF1C1C1C' } };
  titleCell.alignment = { horizontal: 'left', vertical: 'middle' };
  sheet.getRow(1).height = 30;

  sheet.addRow([]);
  sheet.addRow(['Numero Ordine', order.id.slice(0, 8).toUpperCase()]);
  sheet.addRow(['Cliente', order.customer?.companyName || '']);
  sheet.addRow(['Data', new Date(order.createdAt).toLocaleDateString('it-IT')]);
  sheet.addRow(['Stato', order.status]);
  sheet.addRow([]);

  // Column definitions
  sheet.columns = [
    { key: 'code', width: 18 },
    { key: 'name', width: 38 },
    { key: 'famiglia', width: 18 },
    { key: 'sottofamiglia', width: 18 },
    { key: 'linea', width: 18 },
    { key: 'colore', width: 14 },
    { key: 'misura', width: 12 },
    { key: 'produttore', width: 18 },
    { key: 'qty', width: 10 },
    { key: 'unitPrice', width: 16 },
    { key: 'total', width: 14 },
  ];

  // Header row
  const headerRow = sheet.addRow([
    'Codice prodotto', 'Descrizione', 'Famiglia', 'Sottofamiglia',
    'Linea', 'Colore', 'Misura', 'Produttore',
    'Quantità', 'Prezzo unitario', 'Totale riga',
  ]);
  headerRow.font = { bold: true, size: 9, color: { argb: 'FF1C1C1C' } };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFF5EFE6' },
  };
  headerRow.height = 22;
  headerRow.alignment = { vertical: 'middle' };
  headerRow.border = { bottom: { style: 'thin', color: { argb: 'FFE8E2D9' } } };

  // Data rows
  order.items?.forEach((item, i) => {
    const p = item.product as any;
    const row = sheet.addRow({
      code: p?.code || '',
      name: p?.name || '',
      famiglia: p?.famiglia || '',
      sottofamiglia: p?.sottofamiglia || '',
      linea: p?.nomLinea || '',
      colore: p?.colore || '',
      misura: p?.misura || '',
      produttore: p?.produttore || '',
      qty: item.quantity,
      unitPrice: Number(item.unitPrice),
      total: Number(item.subtotal),
    });

    row.getCell('unitPrice').numFmt = '€#,##0.00';
    row.getCell('total').numFmt = '€#,##0.00';
    row.font = { size: 9 };
    row.alignment = { vertical: 'middle' };

    if (i % 2 === 0) {
      row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFAFAF7' } };
    }
  });

  // Total row
  const totalRow = sheet.addRow({
    code: '', name: '', famiglia: '', sottofamiglia: '', linea: '',
    colore: '', misura: '', produttore: 'TOTALE',
    qty: order.totalItems, unitPrice: '', total: Number(order.totalValue),
  });
  totalRow.font = { bold: true, size: 9 };
  totalRow.getCell('total').numFmt = '€#,##0.00';
  totalRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5EFE6' } };
  totalRow.border = { top: { style: 'thin', color: { argb: 'FFCCBBAA' } } };

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
