ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "materiale1_bio" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "materiale2_bio" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "materiale3_bio" BOOLEAN NOT NULL DEFAULT false;
